<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Friday_Sub_Category_Picklist</name>
   <tag></tag>
   <elementGuidId>b8029b2e-4d95-4410-b2f4-6d2b0a9693fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@data-item-id=&quot;combobox-button-225-3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
